name: gerenciador_filmes_app
description: "Um novo projeto Flutter para gerenciar filmes." # Adicione uma descrição
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0' # Use a versão correta do seu SDK Flutter se souber, ou um intervalo mais amplo como este

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  # http: ^1.2.0 # Descomente se for usar API REST

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # ou a versão mais recente que o 'flutter create' gerou

# A seção flutter DEVE estar aqui, no nível raiz do arquivo
flutter:
  uses-material-design: true

  # Para adicionar assets à sua aplicação, adicione uma seção assets, como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg